# Generated by Django 4.2.26 on 2026-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=20)),
                ('system_size', models.IntegerField()),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Walk-in', 'Walk-in'), ('Social Media', 'Social Media')], max_length=20)),
                ('status', models.CharField(choices=[('New Lead', 'New Lead'), ('Contacted', 'Contacted'), ('Site visit scheduled', 'Site visit scheduled'), ('Proposal sent', 'Proposal sent'), ('Won', 'Won'), ('Lost', 'Lost')], default='New Lead', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
